title: Luquelab Website 

### Theme
remote_theme: pmarsceill/just-the-docs

### Color scheme supports "light" (default) and "dark"
color_scheme: light

aux_links:
  "Project Template on GitHub":
    - "//github.com/luquelab/project_template"
    
plugins:
  - jekyll-last-modified-at

last_modified_at: true
